#
# Configuration file to create conda environment to run ITS_LIVE mosaics code.
#
# To create conda environment, run command:
#
# $ conda env create -f mosaics_environment.yml
#
# Followed by the following command to activate the environment:
#
# $ conda activate itslive_mosaics_v2.1
#
name: itslive_mosaics_v2.1

channels:
  - conda-forge

dependencies:
  - python=3.9*
  - dask=2023.1.*
  - geopandas
  - gdal=3.7.0
  - pandas=1.5.*
  - numpy=1.21.*
  - numba=0.56.*
  - h5py=3.9.0
  - h5netcdf
  - requests=2.31.0
  - pyproj
  - xarray==2023.1.*
  - netcdf4
  - flake8
  - scipy==1.9.1
  - s3fs>=2022.1.0
  - fsspec>=2022.1.0
  - boto3=1.39.11
  - shapely=2.0.1
  - tqdm=4.65.0
  - utm
  - zarr=2.17.*
  - pip
  - pip:
    - numpy==1.21.6
    - geojson==3.0.1
    - awscliv2==2.2.0
    - rioxarray==0.15.0
    - taichi==1.5.0
