name: itslivecube_virtualizarr_sep1.2026

channels:
  - conda-forge

dependencies:
  - python
  - dask
  - numpy
  - joblib
  - boto3
  - geopandas
  - rioxarray
  - pyproj
  - jupyterlab
  - h5py
  - h5netcdf
  - xarray
  - flake8
  - scipy
  - shapely
  - tqdm
  - matplotlib
  - s3fs
  - obstore
  - icechunk
  - virtualizarr
  - fastparquet
  - kerchunk
  - zarr
  - awscli
  - pystac-client=0.8    # required by itslive-py
  - python-duckdb=1.3.0  # required by itslive-py
  - rustac>=0.9         # required by itslive-py
  - pip
  - pip:
    - itslive>=0.7.4

